server:
  port: 8080
spring:
  application:
    name: service1-client

grpc:
  client:
    service1-grpc-server:
      address: 'static://127.0.0.1:9091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 9092